In [1]:
import numpy as np
import matplotlib.pyplot as plt

# print statements

In [2]:
print("Hello World!")

Hello World!


# variables

In [4]:
x = 1
y = 10.52
message = "Hello class!"

In [5]:
x

1

In [6]:
y

10.52

In [7]:
message

'Hello class!'

In [10]:
x + y

11.52

In [11]:
int(x + y)

11

In [12]:
4/2

2.0

In [13]:
4/3

1.3333333333333333

In [14]:
4%3

1

In [15]:
a,b,c = 15, 239, 5492
a,b,c

(15, 239, 5492)

# numpy and plotting basics

In [16]:
# creating an array from 0 to 9
x = np.arange(10)

In [19]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# array indices start at zero in python:

In [17]:
x[0]

0

# array index ranges go from first index to second-to-last:

In [20]:
x[0:3] # last index is not included!

array([0, 1, 2])

In [21]:
x[3:7]

array([3, 4, 5, 6])

# arrays are used in a vectorised way; this avoids for-loops:

In [22]:
y = x + 10

In [23]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
y2 = -3*(x-5)**2 - 4

In [25]:
y2

array([-79, -52, -31, -16,  -7,  -4,  -7, -16, -31, -52])

# python functions as defined by a def statement:

In [26]:
def func(x,a,b,c):
    return a + b*x + c*x**2 

In [27]:
y3 = func(x,1,2,3)

In [28]:
y3

array([  1,   6,  17,  34,  57,  86, 121, 162, 209, 262])

# the same function but with an array of parameters:

In [29]:
def func_vec(x,p):
    return p[0] + p[1]*x + p[2]*x**2

In [30]:
y4 = func_vec(x,[1,2,3])

In [31]:
y4-y3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# There is a difference between arrays, vectors, and lists in python;
# lists are collections of numbers, strings, objects, arrays, others lists, ..., e.g.:

In [32]:
b = [1,'y6',np.linspace(0,1,5),['a','b']]

# b[0] is an iteger
# b[1] is a string
# b[2] is a whole numpy array
# b[3] is another list, containing two strings

In [33]:
b[2]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
b[3]

['a', 'b']

In [35]:
b[3][0]

'a'